/////////////////////////////////////////////////////////////////////////////
// Name:        generalsettingsdlg.h
// Purpose:     
// Author:      Julian Smart
// Modified by: 
// Created:     04/12/05 17:11:58
// RCS-ID:      
// Copyright:   (c) Julian Smart
// Licence:     wxWindows License
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Apr 12 2005

#ifndef _GENERALSETTINGSDLG_H_
#define _GENERALSETTINGSDLG_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "generalsettingsdlg.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/spinctrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10002
#define SYMBOL_GENERALSETTINGSPAGE_STYLE 0
#define SYMBOL_GENERALSETTINGSPAGE_TITLE _("General Settings")
#define SYMBOL_GENERALSETTINGSPAGE_IDNAME ID_DIALOG
#define SYMBOL_GENERALSETTINGSPAGE_SIZE wxSize(400, 300)
#define SYMBOL_GENERALSETTINGSPAGE_POSITION wxDefaultPosition
#define ID_CHECKBOX 10013
#define ID_SPINCTRL 10000
#define ID_SPINCTRL1 10014
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif
#ifndef wxFIXED_MINSIZE
#define wxFIXED_MINSIZE 0
#endif

/*!
 * GeneralSettingsPage class declaration
 */

class GeneralSettingsPage: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( GeneralSettingsPage )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    GeneralSettingsPage( );
    GeneralSettingsPage( wxWindow* parent, wxWindowID id = SYMBOL_GENERALSETTINGSPAGE_IDNAME, const wxPoint& pos = SYMBOL_GENERALSETTINGSPAGE_POSITION, const wxSize& size = SYMBOL_GENERALSETTINGSPAGE_SIZE, long style = SYMBOL_GENERALSETTINGSPAGE_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_GENERALSETTINGSPAGE_IDNAME, const wxPoint& pos = SYMBOL_GENERALSETTINGSPAGE_POSITION, const wxSize& size = SYMBOL_GENERALSETTINGSPAGE_SIZE, long style = SYMBOL_GENERALSETTINGSPAGE_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

    /// Transfers data from window
    virtual bool TransferDataFromWindow();

////@begin GeneralSettingsPage event handler declarations

////@end GeneralSettingsPage event handler declarations

////@begin GeneralSettingsPage member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end GeneralSettingsPage member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin GeneralSettingsPage member variables
////@end GeneralSettingsPage member variables
};

#endif
    // _GENERALSETTINGSDLG_H_
